### ISSUE TITLE
Cannot generate cookiecutter-webpack on windows

### ISSUE THREAD

**Issue by imexlava** [hzdg/cookiecutter-webpack#15]
Hi all,

I failed running cookiecutter-webpack on windows, here is the error message:
 D:\temps>cookiecutter git@github.com:hzdg/cookiecutter-webpack.git
Cloning into 'cookiecutter-webpack'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "c:\anaconda2\envs\klinik\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda2\envs\klinik\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda2\envs\klinik\Scripts\cookiecutter.exe__main__.py", line 9, in <module>
  File "c:\anaconda2\envs\klinik\lib\site-packages\click\core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "c:\anaconda2\envs\klinik\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\anaconda2\envs\klinik\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "c:\anaconda2\envs\klinik\lib\site-packages\click\core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "c:\anaconda2\envs\klinik\lib\site-packages\cookiecutter\cli.py", line 106, in main
    config_file=user_config
  File "c:\anaconda2\envs\klinik\lib\site-packages\cookiecutter\main.py", line 107, in cookiecutter
    no_input=no_input
  File "c:\anaconda2\envs\klinik\lib\site-packages\cookiecutter\vcs.py", line 119, in clone
    subprocess.check_call([repo_type, 'clone', repo_url], cwd=clone_to_dir)
  File "c:\anaconda2\envs\klinik\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'git', u'clone', u'git@github.com:hzdg/cookiecutter-webpack.git']' returned non-zero exit status 128

D:\temps>cookiecutter --version
Cookiecutter 1.4.0 from c:\anaconda2\envs\klinik\lib\site-packages (Python 2.7)

 D:\temps>git --version
git version 2.5.0.windows.1

Any suggestion ?

thankyou

**Comment by goldhand** [comment]
Have you tried `$ cookiecutter https://github.com/hzdg/cookiecutter-webpack.git`?

let me know if that works

**Comment by imexlava** [comment]
@goldhand : it's works, thank you.

**Comment by goldhand** [comment]
fyi you need to authenticate through git if you want to use ssh to clone
